//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRecipeBook.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErroMessagesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErroMessagesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyRecipeBook.Exceptions.ErroMessagesResource", typeof(ErroMessagesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do login again.
        /// </summary>
        public static string Token_Expired {
            get {
                return ResourceManager.GetString("Token_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow Error.
        /// </summary>
        public static string Unknown_Error {
            get {
                return ResourceManager.GetString("Unknown_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already taken.
        /// </summary>
        public static string User_Email_Already_Taken {
            get {
                return ResourceManager.GetString("User_Email_Already_Taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email can&apos;t be empty.
        /// </summary>
        public static string User_Email_Empty {
            get {
                return ResourceManager.GetString("User_Email_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email invalid.
        /// </summary>
        public static string User_Email_Invalid {
            get {
                return ResourceManager.GetString("User_Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User unregistered.
        /// </summary>
        public static string User_Email_Unregistered {
            get {
                return ResourceManager.GetString("User_Email_Unregistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or Password incorrect.
        /// </summary>
        public static string User_Login_Invalid {
            get {
                return ResourceManager.GetString("User_Login_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username can&apos;t be empty.
        /// </summary>
        public static string User_Name_Empty {
            get {
                return ResourceManager.GetString("User_Name_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the user.
        /// </summary>
        public static string User_Not_Found {
            get {
                return ResourceManager.GetString("User_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password can&apos;t be empty.
        /// </summary>
        public static string User_Password_Empty {
            get {
                return ResourceManager.GetString("User_Password_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual password invalid.
        /// </summary>
        public static string User_Password_Invalid {
            get {
                return ResourceManager.GetString("User_Password_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should be contain 6 characters.
        /// </summary>
        public static string User_Password_MinChar {
            get {
                return ResourceManager.GetString("User_Password_MinChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone can&apos;t be empty.
        /// </summary>
        public static string User_Phone_Empty {
            get {
                return ResourceManager.GetString("User_Phone_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number invalid. Should be: (xx) x xxxx - xxxx.
        /// </summary>
        public static string User_Phone_Invalid {
            get {
                return ResourceManager.GetString("User_Phone_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe category invalid.
        /// </summary>
        public static string User_Recipe_Category_Invalid {
            get {
                return ResourceManager.GetString("User_Recipe_Category_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe should have ingredients.
        /// </summary>
        public static string User_Recipe_Ingredients_Empty {
            get {
                return ResourceManager.GetString("User_Recipe_Ingredients_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ingredients duplicated.
        /// </summary>
        public static string User_Recipe_Ingredients_Product_Duplicate_Erro {
            get {
                return ResourceManager.GetString("User_Recipe_Ingredients_Product_Duplicate_Erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients product should not be empty.
        /// </summary>
        public static string User_Recipe_Ingredients_Product_Empty {
            get {
                return ResourceManager.GetString("User_Recipe_Ingredients_Product_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients quantity should not be empty.
        /// </summary>
        public static string User_Recipe_Ingredients_Quantity_Empty {
            get {
                return ResourceManager.GetString("User_Recipe_Ingredients_Quantity_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe not found.
        /// </summary>
        public static string User_Recipe_Not_Found {
            get {
                return ResourceManager.GetString("User_Recipe_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe preparation method should not be empty.
        /// </summary>
        public static string User_Recipe_Preparation_Method_Empty {
            get {
                return ResourceManager.GetString("User_Recipe_Preparation_Method_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparation time invalid.
        /// </summary>
        public static string User_Recipe_Preparation_Time_Invalid {
            get {
                return ResourceManager.GetString("User_Recipe_Preparation_Time_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe title should not be empty.
        /// </summary>
        public static string User_Recipe_Title_Empty {
            get {
                return ResourceManager.GetString("User_Recipe_Title_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized user.
        /// </summary>
        public static string User_Unauthorized {
            get {
                return ResourceManager.GetString("User_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot execute this operation.
        /// </summary>
        public static string User_Unauthorized_Operation {
            get {
                return ResourceManager.GetString("User_Unauthorized_Operation", resourceCulture);
            }
        }
    }
}
